steps:
# build the Java app and package it into a jar
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
# use the Dockerfile to create a container image
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/game-of-life", "--build-arg=JAR_FILE=target/game-of-life-1.0-SNAPSHOT.jar", "."]
# push the container image to the Registry
- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/$PROJECT_ID/game-of-life"]
#deploy to Google Cloud Run
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  containers:
  - image: gcr.io/$PROJECT_ID/game-of-life:1.0
    ports:
    - name: 'gcr.io/cloud-builders/gcloud'
      containerPort: 8080
      region: us-east1
    resources:
      limits:
        memory: 256Mi
        cpu: 1000m 
  #args: ['run', 'deploy', 'game-of-life', '--image', 'gcr.io/$PROJECT_ID/game-of-life', '--region', 'us-east1', '--platform', 'managed']
#images: ["gcr.io/$PROJECT_ID/game-of-life"]

  
